# -*- coding: utf-8 -*-
"""PandasProfiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_q55BpOZfDmcOavQgjc9wyoYcS-Ju6Q8
"""

import pandas as pd

df = pd.read_csv('Titanic-Dataset.csv')

df.head()

pip install pandas-profiling

!pip install ydata-profiling
from ydata_profiling import ProfileReport

prof = ProfileReport(df)
prof.to_file(output_file='output.html')

